Repository felangel/equatable, pull requests merged in 2020-07, with the labels that each got.

#76 Iterable hashCode fix
  lib/src/equatable_utils.dart
  test/equatable_test.dart
Labels: bug

#78 docs: improve and fix public docs
  lib/equatable.dart
  lib/src/equatable.dart
  lib/src/equatable_config.dart
  lib/src/equatable_mixin.dart
Labels: documentation

#79 refactor: v1.2.3
  CHANGELOG.md
  README.md
  analysis_options.yaml
  example/main.dart
  lib/src/equatable.dart
  lib/src/equatable_config.dart
  lib/src/equatable_mixin.dart
  lib/src/equatable_utils.dart
  performance_tests/README.md
  performance_tests/main.dart
  performance_tests/pubspec.yaml
  pubspec.yaml
  test/custom_list.dart
  test/equatable_config_test.dart
  test/equatable_mixin_test.dart
  test/equatable_test.dart
Labels: documentation, enhancement
