Repository felangel/equatable, pull requests merged in 2021-02, with the labels that each got.

#103 fix: iterable equality comparisons
  lib/src/equatable_utils.dart
  test/equatable_mixin_test.dart
  test/equatable_test.dart
Labels: bug

#97 fix: stringify instance with long properties
  lib/src/equatable_utils.dart
  test/equatable_test.dart
Labels: bug

#105 docs: Make constructor constants
  README.md
Labels: documentation

#106 docs: migration docs change
  doc/migration_guides/migration-0.6.0.md
Labels: documentation

#109 feat!: stringify defaults to true in debug mode
  .github/workflows/main.yaml
  CHANGELOG.md
  README.md
  lib/src/equatable_config.dart
  pubspec.yaml
  test/equatable_config_test.dart
  test/equatable_mixin_test.dart
  test/equatable_test.dart
Labels: enhancement

#108 fix: support legacy equality overrides
  lib/src/equatable_mixin.dart
  test/equatable_mixin_test.dart
Labels: bug
