Repository felangel/equatable, pull requests merged in 2024-11, with the labels that each got.

#173 perf: improve equality comparison performance
  benchmarks/README.md
  benchmarks/pubspec.yaml
  lib/src/equatable.dart
  lib/src/equatable_mixin.dart
  lib/src/equatable_utils.dart
  test/equatable_utils_test.dart
Labels: enhancement

#185 chore: v2.0.6
  CHANGELOG.md
  LICENSE
  pubspec.yaml
Labels: chore

#189 fix: explicitly handle `num` equality comparisons
  lib/src/equatable_utils.dart
  test/equatable_utils_test.dart
Labels: bug

#190 revert: `equals` in `equatable_utils`
  lib/src/equatable_utils.dart
  test/equatable_utils_test.dart
Labels: chore

#191 chore: v2.0.7
  CHANGELOG.md
  pubspec.yaml
Labels: chore
